version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-market
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234.p
      MYSQL_DATABASE: market
    ports:
      - "3306:3306"
    networks:
      - ecommerce-network

  microservicio_productos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservicio_productos
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/market
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234.p
      SERVER_PORT: 8084
    ports:
      - "8084:8084"
    depends_on:
      - mysql
    networks:
      - ecommerce-network

  microservice_clientes:
    build:
      context: .
      dockerfile: Dockerfile-clientes
    container_name: microservice_clientes
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/market
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234.p
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - ecommerce-network

  microservicio_pedidos:
    build:
      context: .
      dockerfile: Dockerfile-pedidos
    container_name: microservicio_pedidos
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/market
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234.p
      SERVER_PORT: 8002
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge